function required<T extends Element>(id: string): T {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Expected #${id} to exist in the document`);
  return el as unknown as T;
}

export function getElements() {
  return {
    // Header
    themeToggle: required<HTMLButtonElement>("themeToggle"),
    oauthSigninBtn: required<HTMLButtonElement>("oauthSigninBtn"),
    oauthSignedIn: required<HTMLDivElement>("oauthSignedIn"),
    oauthAvatar: required<HTMLSpanElement>("oauthAvatar"),
    oauthUsername: required<HTMLElement>("oauthUsername"),
    oauthSignoutBtn: required<HTMLButtonElement>("oauthSignoutBtn"),

    // Source picker (the merged card's first half)
    sourcePicker: required<HTMLDivElement>("sourcePicker"),
    srcSeg: required<HTMLDivElement>("srcSeg"),
    localPane: required<HTMLDivElement>("localPane"),
    browsePane: required<HTMLDivElement>("browsePane"),
    browseFilter: required<HTMLInputElement>("browseFilter"),
    browseStatus: required<HTMLDivElement>("browseStatus"),
    browseDandisets: required<HTMLUListElement>("browseDandisets"),
    browseVideoHeading: required<HTMLSpanElement>("browseVideoHeading"),
    browseDandisetLink: required<HTMLAnchorElement>("browseDandisetLink"),
    browseVideos: required<HTMLUListElement>("browseVideos"),
    emberPane: required<HTMLDivElement>("emberPane"),
    emberUrl: required<HTMLInputElement>("emberUrl"),
    emberLoadBtn: required<HTMLButtonElement>("emberLoadBtn"),
    dropzone: required<HTMLDivElement>("dropzone"),
    browseVideoBtn: required<HTMLButtonElement>("browseVideoBtn"),
    videoFile: required<HTMLInputElement>("videoFile"),
    slpFile: required<HTMLInputElement>("slpFile"),
    slpToggle: required<HTMLInputElement>("slpToggle"),

    // Player (the merged card's second half)
    playerCard: required<HTMLElement>("playerCard"),
    playerControls: required<HTMLDivElement>("playerControls"),
    loadedSource: required<HTMLDivElement>("loadedSource"),
    loadedSourceName: required<HTMLSpanElement>("loadedSourceName"),
    btnChangeVideo: required<HTMLButtonElement>("btnChangeVideo"),
    modeSeg: required<HTMLDivElement>("modeSeg"),
    showPoseRow: required<HTMLLabelElement>("showPoseRow"),
    showPose: required<HTMLInputElement>("showPose"),
    stage: required<HTMLDivElement>("stage"),
    emptyStage: required<HTMLDivElement>("emptyStage"),
    view: required<HTMLCanvasElement>("view"),
    overlayInfo: required<HTMLDivElement>("overlayInfo"),
    stageBusy: required<HTMLDivElement>("stageBusy"),
    stageBusyLabel: required<HTMLSpanElement>("stageBusyLabel"),
    stageBusyDetail: required<HTMLSpanElement>("stageBusyDetail"),
    selbar: required<HTMLDivElement>("selbar"),
    selfill: required<HTMLDivElement>("selfill"),
    inHandle: required<HTMLDivElement>("inHandle"),
    outHandle: required<HTMLDivElement>("outHandle"),
    playHandle: required<HTMLDivElement>("playHandle"),
    blurLayer: required<HTMLDivElement>("blurLayer"),
    blurTools: required<HTMLDivElement>("blurTools"),
    blurAddBtn: required<HTMLButtonElement>("blurAddBtn"),
    blurRadiusRange: required<HTMLInputElement>("blurRadiusRange"),
    blurRadiusValue: required<HTMLInputElement>("blurRadiusValue"),
    blurRemoveBtn: required<HTMLButtonElement>("blurRemoveBtn"),
    blurClearBtn: required<HTMLButtonElement>("blurClearBtn"),
    blurHint: required<HTMLParagraphElement>("blurHint"),
    selRuler: required<HTMLDivElement>("selruler"),
    overviewWrap: required<HTMLDivElement>("overviewWrap"),
    windowGroup: required<HTMLDivElement>("windowGroup"),
    windowSeg: required<HTMLDivElement>("windowSeg"),
    overBar: required<HTMLDivElement>("overbar"),
    overWin: required<HTMLDivElement>("overwin"),
    overSel: required<HTMLDivElement>("oversel"),
    overPlay: required<HTMLDivElement>("overplay"),
    overRuler: required<HTMLDivElement>("overruler"),
    btnPrev: required<HTMLButtonElement>("btnPrev"),
    btnPlay: required<HTMLButtonElement>("btnPlay"),
    btnNext: required<HTMLButtonElement>("btnNext"),
    speedSeg: required<HTMLDivElement>("speedSeg"),
    inVal: required<HTMLInputElement>("inVal"),
    curVal: required<HTMLInputElement>("curVal"),
    outVal: required<HTMLInputElement>("outVal"),
    btnClearSel: required<HTMLButtonElement>("btnClearSel"),

    // SLEAP annotations card
    slpCard: required<HTMLElement>("slpCard"),
    slpDropzone: required<HTMLDivElement>("slpDropzone"),
    browseSlpBtn: required<HTMLButtonElement>("browseSlpBtn"),
    slpError: required<HTMLDivElement>("slpError"),
    slpErrorTitle: required<HTMLParagraphElement>("slpErrorTitle"),
    slpErrorList: required<HTMLUListElement>("slpErrorList"),
    slpWarning: required<HTMLDivElement>("slpWarning"),
    slpWarningTitle: required<HTMLParagraphElement>("slpWarningTitle"),
    slpWarningList: required<HTMLUListElement>("slpWarningList"),
    slpStatus: required<HTMLDivElement>("slpStatus"),
    slpNameLabel: required<HTMLSpanElement>("slpNameLabel"),
    slpBadge: required<HTMLSpanElement>("slpBadge"),
    btnChangePose: required<HTMLButtonElement>("btnChangePose"),

    // Delivery card (Download / Upload)
    deliverCard: required<HTMLElement>("deliverCard"),
    deliverToggleRow: required<HTMLDivElement>("deliverToggleRow"),
    deliverSeg: required<HTMLDivElement>("deliverSeg"),
    selectionDescription: required<HTMLTextAreaElement>("selectionDescription"),
    uploadOriginalRow: required<HTMLLabelElement>("uploadOriginalRow"),
    uploadOriginal: required<HTMLInputElement>("uploadOriginal"),
    blurOriginalNote: required<HTMLParagraphElement>("blurOriginalNote"),
    downloadPane: required<HTMLDivElement>("downloadPane"),
    downloadHint: required<HTMLParagraphElement>("downloadHint"),
    downloadPreview: required<HTMLParagraphElement>("downloadPreview"),
    downloadPreviewName: required<HTMLElement>("downloadPreviewName"),
    btnDownload: required<HTMLButtonElement>("btnDownload"),
    downloadStatus: required<HTMLSpanElement>("downloadStatus"),

    // Upload destination
    uploadPane: required<HTMLDivElement>("uploadPane"),
    dandisetId: required<HTMLSelectElement>("dandisetId"),
    dandisetMessage: required<HTMLParagraphElement>("dandisetMessage"),
    dandisetSingle: required<HTMLParagraphElement>("dandisetSingle"),
    dandisetSingleText: required<HTMLSpanElement>("dandisetSingleText"),
    dandisetEmbargoError: required<HTMLParagraphElement>("dandisetEmbargoError"),
    humanSubjectsBanner: required<HTMLDivElement>("humanSubjectsBanner"),
    humanSubjectsUnconfirmed: required<HTMLDivElement>("humanSubjectsUnconfirmed"),
    humanSubjectsConfirmBtn: required<HTMLButtonElement>("humanSubjectsConfirmBtn"),
    humanSubjectsConfirmed: required<HTMLParagraphElement>("humanSubjectsConfirmed"),
    viewDatasetLink: required<HTMLAnchorElement>("viewDatasetLink"),
    btnUpload: required<HTMLButtonElement>("btnUpload"),
    uploadStatus: required<HTMLSpanElement>("uploadStatus"),
    uploadProgress: required<HTMLDivElement>("uploadProgress"),
    uploadProgressFill: required<HTMLDivElement>("uploadProgressFill"),

    // Footer
    versionIndicator: required<HTMLAnchorElement>("version-indicator"),
  };
}

export type ClipExtractorElements = ReturnType<typeof getElements>;
